Respect XDG_CONFIG_HOME for policy.json
containers/image pull request #1011
Opened 2020-08-08 20:39 UTC by davidscherer

The default path for (rootless) policy.json should respect XDG_CONFIG_HOME if present, as the paths for other configuration files like storage.conf and containers.conf do.

See also https://github.com/containers/common/pull/248

2020-08-08 20:47 UTC, TomSweeneyRedHat commented
@davidscherer looks like you've some whitespace issues somewhere.   `gofmt -s -w filename.go` and then add/commit/rebase/push should fix it.

2020-08-09 12:53 UTC, rhatdan commented on signature/policy_config.go
> +	configHomeDir := os.Getenv("XDG_CONFIG_HOME")
Please use containers/storage/pkg/homedir GetConfigHome()

2020-08-10 09:26 UTC, mtrmac requested changes
This would currently break non-Linux systems, where `GetConfigHome` always fails. I don’t know what’s the right thing to do on Windows (probably not hard-coding `.config`), or whether we care much, but on macOS it really should be possible to use a per-user path, and by now it would break users to change the default.

At a first glance, `homedir.GetConfigHome` should probably use the hard-coded `.config` (it does fall back to that path on Linux already!) on non-XDG systems, or at least on non-XDG Unixes — but I haven’t looked at all at any other users to see whether it would be safe.

2021-03-23 18:32 UTC, rhatdan commented
@davidscherer @vrothberg @mtrmac what should we do with this PR?

2021-03-23 21:40 UTC, davidscherer commented
I have been happily using the patch from the first commit to this PR, which fixes the problem on Linux, is probably better than nothing on OS X, and as far as I know doesn't cause problems on Windows.

I made the requested change to use GetConfigHome, but that function turns out to be unimplemented on Windows.

So the options are, I suppose:

1. Merge my original change
2. Implement and test GetConfigHome for Windows

There's a case to be made for (2), but I am not in a great position to do it.  IMO (1) is an improvement over the status quo, and the conflicts look easy to resolve.

2022-03-18 15:56 UTC, wwilson commented
What are the current obstacles to getting this merged?

2022-03-19 16:17 UTC, mtrmac commented
Thanks for the ping; it turns out that c/storage/pkg/homedir is no longer hard-failing on non-Linux systems, after commit e2cffe5c610054b088029431230d4143a0e6b1e5 , so this might now be possible to do.

Given that, the PR would need to be updated to be testable without relying on external state (i.e. to turn defaultPolicyPathWithHomeDir into something like `defaultPolicyPathWithConfigHomeDir`), and then to make sure the test coverage is as good as it can get.

2024-10-04 14:33 UTC, wwilson commented
4 years later this is still an issue, and we are still happily applying our patch. Is there any interest in trying to get this upstreamed so that the rest of the world doesn't hit this issue too?

2024-10-04 16:37 UTC, mtrmac commented
The code is using exactly the documented path, so this is being tracked as a feature request, not a bug.

Sure, it would be nice to have that feature; but we do need ~perfect tests in this security-critical package, and it’s not something I can work on myself in the immediate future.

2025-08-26 14:01 UTC, jankaluza commented
Hi, and thank you for your contribution!

We’ve recently migrated this repository into a new **monorepo**: [containers/container-libs](https://github.com/containers/container-libs) along with other repositories

As part of this migration, this repository is no **longer accepting new Pull-Requests** and therefore this Pull-Request is being closed.

Thank you very much for your contribution. We would appreciate your continued help in migrating this PR to the new [container-libs repository](https://github.com/containers/container-libs). Please let us know if you are facing any issues.

You can read more about the migration and the reasoning behind it in our blog post: [Upcoming migration of three containers repositories to monorepo](https://blog.podman.io/2025/08/upcoming-migration-of-three-containers-repositories-to-monorepo/).

Thanks again for your work and for supporting the containers ecosystem!

2025-08-26 14:01 UTC, closed without merging