Skip checking if the manifest difest matches for docker-daemon source. Fixes #1049
containers/image pull request #1050
Opened 2020-09-22 11:54 UTC by airadier

As described in https://github.com/containers/image/issues/1049, the manifest digest specified in the repo@sha256:digest won't match the digest calculated from the locally generated manifest when using docker-daemon source.

This fix skips the verification for docker-daemon source.

2020-09-24 08:50 UTC, mtrmac requested changes
Thanks for the PR.

We shouldn’t have exceptions like this in the code, it will be very difficult to trace back unexpected behavior to this condition.

My first guess is that `.DockerReference` should just not return a value if it can’t return a working value, but I’ll need to take a closer look at how the method is used in callers of c/image (sadly it’s not very well-defined what the value is intended to be used for).

2022-02-10 22:44 UTC, mtrmac commented
Changing the `DockerReference` method of the `docker-daemon:` transport is the available way to represent the situation in the current API.

Alternatively, yes, a transport declaring that the digests from `DockerReference` are not to be validated is an option.

_Either way_ that affects semantics in caller-visible ways, so we need to at least audit existing users in the GitHub.com/containers ecosystem.

2022-08-11 08:03 UTC, universam1 commented
example issue: `podman pull ghcr.io/fluxcd/flagger:1.22.1`

Any workaround possible?

2022-08-16 19:54 UTC, mtrmac commented
@universam1 That seems completely unrelated to the `docker-daemon` problem in the original PR. Please file a separate report, against Podman, and include actual/expected results and logs.

2025-08-26 14:01 UTC, jankaluza commented
Hi, and thank you for your contribution!

We’ve recently migrated this repository into a new **monorepo**: [containers/container-libs](https://github.com/containers/container-libs) along with other repositories

As part of this migration, this repository is no **longer accepting new Pull-Requests** and therefore this Pull-Request is being closed.

Thank you very much for your contribution. We would appreciate your continued help in migrating this PR to the new [container-libs repository](https://github.com/containers/container-libs). Please let us know if you are facing any issues.

You can read more about the migration and the reasoning behind it in our blog post: [Upcoming migration of three containers repositories to monorepo](https://blog.podman.io/2025/08/upcoming-migration-of-three-containers-repositories-to-monorepo/).

Thanks again for your work and for supporting the containers ecosystem!

2025-08-26 14:01 UTC, closed without merging