Add filepath.Clean at various path
containers/image pull request #2162
Opened 2023-10-30 06:43 UTC by divyansh42

Was going through the code and I think it would be better to provide path after passing through `filepath.Clean()`. Therefore, I made the required changes.
Please let me know your thoughts on the same.

2023-10-30 14:34 UTC, rhatdan commented
Thanks @divyansh42 
LGTM
@mtrmac @vrothberg PTAL

2023-10-30 14:36 UTC, mtrmac requested changes
Why is this wanted?

`filepath.Clean` changes semantics of the path on Unix, so _by default_ it is undesirable.

2023-10-30 14:39 UTC, mtrmac commented on docker/docker_image_src.go
> +		sigBlob, err := os.ReadFile(filepath.Clean(sigURL.Path))
… and it is actively misleading to log one path and read another.

2023-10-31 19:11 UTC, TomSweeneyRedHat commented
I'm hesitant to add this as @mtrmac noted, it does change the path.  That might be good, might not.  However, if we decide to keep it, we should also clean the path in the log too.

2023-11-27 22:22 UTC, closed without merging