docker: support for requesting chunks without end offset
containers/image pull request #2391
Opened 2024-05-02 14:16 UTC by giuseppe

if the specified length for the range is set to -1, then request all the data possible by using the "Range: <unit>=<range-start>-" syntax for the HTTP range.

2024-05-02 14:34 UTC, mtrmac requested changes
Thanks!

- How this is happening? I can’t see any c/storage caller setting this to -1 .
- The `Length == MaxUint64` semantics is, AFAICS, not documented, and at least `mergeMissingChunks` is doing ordinary arithmetic on the values.
- If this should exist at all,  `blobChunkAccessorProxy`, `splitHTTP200ResponseToPartial`, `streamChunksFromFile` do not handle the special case.

2024-05-02 14:58 UTC, giuseppe commented
the error I am seeing is that we pass the value `-1` to 

> * How this is happening? I can’t see any c/storage caller setting this to -1 .

the problem is here https://github.com/containers/storage/blob/main/pkg/chunked/storage_linux.go#L1611-L1617

in some cases the blobSize is set to -1 from c/image, e.g. when pulling `quay.io/libpod/alpine-with-seccomp:label`.

I could change the code to not use any range (if there are no ranges, then request the whole file), but I thought this would be more flexible.  We can restrict it so that only the last chunk can have len=-1

2024-05-02 16:58 UTC, mtrmac commented
OK, so this is
- a schema1 image (unknown layer size)
- the transparent conversion path (needs to read the full file)
- `ImageSourceSeekable` not having a “read all” method at all.

Pedantically, when the size is unknown, while `GetDiffer` requires it (all three implementations currently do, and there is no “unknown” value documented, the locally correct thing to do is for `PutBlobPartial` to fail without even trying.

If you do want the conversion path to work on these images… yes, I think adding the “length unknown” case to `ImageSourceSeekable` / `BlobChunkAccessor` is the simplest approach. (Notably `blobChunkAccessorProxy` is simpler when there is only one API to call, having to add a whole separate “no-partial download” case to that would not be worth it). So, document the field value, allow it only for the last chunk.

----

But, at a higher level, this is really another argument to say that the transparent conversion should not be via `PutBlobPartial`/`GetDiffer` at all: let it work like an ordinary non-chunked pull, letting c/image deal with the whole blob and digest verification, and then do the conversion all the way down in overlay’s `ApplyDiff`.

2024-05-02 19:23 UTC, giuseppe commented
> OK, so this is
> 
> * a schema1 image (unknown layer size)
> * the transparent conversion path (needs to read the full file)
> * `ImageSourceSeekable` not having a “read all” method at all.
> 
> Pedantically, when the size is unknown, while `GetDiffer` requires it (all three implementations currently do, and there is no “unknown” value documented, the locally correct thing to do is for `PutBlobPartial` to fail without even trying.
> 
> If you do want the conversion path to work on these images… yes, I think adding the “length unknown” case to `ImageSourceSeekable` / `BlobChunkAccessor` is the simplest approach. (Notably `blobChunkAccessorProxy` is simpler when there is only one API to call, having to add a whole separate “no-partial download” case to that would not be worth it). So, document the field value, allow it only for the last chunk.
> 
> But, at a higher level, this is really another argument to say that the transparent conversion should not be via `PutBlobPartial`/`GetDiffer` at all: let it work like an ordinary non-chunked pull, letting c/image deal with the whole blob and digest verification, and then do the conversion all the way down in overlay’s `ApplyDiff`.

we need to be able to pull via the `PutBlobPartial` when `convert_images` is enabled.  composefs needs it to calculate the digests and enable fs-verity for each file.

2024-05-02 19:38 UTC, mtrmac commented
As far as c/image is concerned, with `UncompressedDigest` known, the layer’s `singleLayerIDComponent` is going to be the DiffID, and the ComposeFS usage is ~invisible to c/image. I naively imagine that whether the call stack says `GetDiffer` or `ApplyDiff` does not really matter for fs-verity and other work.

---

One change that _does_ make a difference, however, is that `GetDiffer` is parallelized over up to 6 layers concurrently, but layer commit is sequential. That might well be a very strong reason to do the conversion in `GetDiffer`, not in the commit phase, I didn’t try to measure that.

If this does help, arguably the layer extraction should be similarly made concurrent for non-chunked/non-ComposeFS layers as well. But that redesign would really be a very different conversation (and we might end up deprecating non-ComposeFS layers before that).

2024-05-03 10:14 UTC, giuseppe commented
I've tried adding a new method `GetBlob` to retrieve the entire blob, but I think the current API is more flexible, with a minimal change.

I've updated the comments

2024-05-03 18:38 UTC, mtrmac reviewed
Thanks. The existing code LGTM, but other parts need updating as well.

2024-05-03 18:38 UTC, mtrmac commented on copy/progress_bars.go
>  	rc, errs, err := s.wrapped.GetBlobAt(ctx, info, chunks)
The implementation below needs updating as well.

2024-05-03 18:38 UTC, mtrmac commented on pkg/blobcache/src.go
> +// fully fetches the remaining data from the offset to the end of the blob.
The implementation (`streamChunksFromFile`) needs updating as well.

2024-05-03 18:38 UTC, mtrmac commented on internal/private/private.go
> +	// fully fetches the remaining data from the offset to the end of the blob.
(Documenting it in the `ImageSourceChunk.Length` field might be helpful, and perhaps sufficient.)

2024-05-03 18:38 UTC, mtrmac commented on docker/docker_image_src.go
> +			return nil, nil, fmt.Errorf("invalid chunk requested: %v", c)
There might not be anything invalid about `c` itself.

Something like `“internal error: another chunk requested after an util-EOF chunk”`?

2024-05-03 18:38 UTC, mtrmac commented on docker/docker_image_src.go
> +			reader = body
Non-blocking:
```suggestion
			reader = body // The caller has ensured that this is the last requested chunk
```

2024-05-03 20:17 UTC, giuseppe commented
thanks, addressed your comments in the last version

2024-05-13 18:57 UTC, rhatdan commented
Seems like there is one comment by @mtrmac that was not addressed?

2024-05-13 19:26 UTC, giuseppe commented
> Seems like there is one comment by @mtrmac that was not addressed?

I thought I've addressed them all, which one is still missing?

2024-05-13 20:55 UTC, rhatdan commented
https://github.com/containers/image/pull/2391/files#r1589601556

2024-05-14 08:37 UTC, giuseppe commented
> https://github.com/containers/image/pull/2391/files#r1589601556

Thanks.  Fixed now

2024-05-14 08:57 UTC, mtrmac approved these changes
Thanks!

2024-05-14 08:57 UTC, merged