Export BuiltinDefaultPolicyPath
containers/image pull request #2562
Opened 2024-09-06 11:41 UTC by rhatdan

This field is duplicated in containers/common/pkg/config and is being vendored into bindings, just because it is not exported from containers/image.

2024-09-06 11:42 UTC, rhatdan commented
@mtrmac @Luap99 PTAL

2024-09-06 12:22 UTC, Luap99 reviewed
LGTM

2024-09-06 12:51 UTC, mtrmac requested changes
NAK; if the goal is to handle https://github.com/containers/image/issues/1726 , this is going in the wrong direction, motivating users _even more_ to hard-code specifics of the logic (in this case, exporting the system-wide path motivates users to reimplement the per-user path).

If c/common intends to use the c/image default, it should not be setting the path in `SystemContext` at all, and the whole need for this goes away. (That can’t _immediately_ happen because the two implementations have already diverged. Also _maybe_ c/image needs some special knowledge of rootless operations .)

---

There is `pkg/trust`, which _writes_ to the config files, and that one really needs to know a path, not a policy accessor. So c/image should probably export _something_ — but it wouldn’t be `systemDefaultPolicyPath`; it would be `defaultPolicyPath` or maybe a separate “system-wide primary policy config path” / “per-user primary config path”.

2024-09-09 19:56 UTC, rhatdan commented
Well how do we move forward on that then?

2024-09-09 20:27 UTC, mtrmac commented
I don’t immediately know; the way the code has already diverged, maybe there is some neat elegant solution which is compatible enough, maybe we will have to live with a gross hack forever. Someone needs to figure that out.

---

For the purpose of trimming https://github.com/containers/podman/pull/23857#issuecomment-2328356840 , the bindings should not be including the whole implementation in `pkg/trust` in the first place; AFAICS they just need the `trust.Policy` data type. That can either be split into a subpackage; or the `domain/entities/types` subpackage could define a separate RPC-only type, separate from the implementation type; or maybe `pkg/trust` should be importing the type from `domain/entities/types` — I don’t know what is the general Podman approach to RPC-only types duplicated with implementation types, vs. sharing the two, and where the definitions live.

2025-08-26 14:06 UTC, jankaluza commented
Hi, and thank you for your contribution!

We’ve recently migrated this repository into a new **monorepo**: [containers/container-libs](https://github.com/containers/container-libs) along with other repositories

As part of this migration, this repository is no **longer accepting new Pull-Requests** and therefore this Pull-Request is being closed.

Thank you very much for your contribution. We would appreciate your continued help in migrating this PR to the new [container-libs repository](https://github.com/containers/container-libs). Please let us know if you are facing any issues.

You can read more about the migration and the reasoning behind it in our blog post: [Upcoming migration of three containers repositories to monorepo](https://blog.podman.io/2025/08/upcoming-migration-of-three-containers-repositories-to-monorepo/).

Thanks again for your work and for supporting the containers ecosystem!

2025-08-26 14:06 UTC, closed without merging