registry: remove ping v1
containers/image pull request #2588
Opened 2024-10-01 15:02 UTC by carlosrodfern

The ping v1 happens when the ping v2 fails, however, it causes the ping v2 error to be skipped and not output to the user. As result, when a registry has v1 and v2 enabled, and there are, for example, intermittent connectivity issues making the ping v2 fail, the user is presented with a misleading error saying "can't talk to V1 registry."

Since the only use of v1 is for the search API as a workaround for docker.io, and new container registries setups are very unlikely to be v1-only, there is little utility in keeping this v1 detection in the attempt to help the user realize their setup is v1-only, hence not compatible. On the contratry, it just presents the user with a misleading error in certain circumstances.

2024-10-01 17:38 UTC, cgwalters commented
/approve

Makes sense to me...

2024-10-01 17:54 UTC, mtrmac requested changes
Thanks!

This makes sense to me, but we must not break API.

2024-10-01 17:54 UTC, mtrmac commented on docker/errors.go
> -	ErrV1NotSupported = errors.New("can't talk to a V1 container registry")
This is a public API and can’t be removed, even if it will never match anything.

Adding a `Deprecated:` comment would be useful.

2024-10-01 17:54 UTC, mtrmac commented on types/types.go
> -	DockerDisableV1Ping bool
This is a public API and can’t be removed.

Adding a `Deprecated:` comment would be useful.

2024-10-01 17:54 UTC, mtrmac commented on docker/docker_client.go
> -		err = fmt.Errorf("pinging container registry %s: %w", c.registry, err)
I think we still want this wrapping to happen.

2024-10-01 17:54 UTC, mtrmac commented on docker/docker_client.go
> -			pingURL, err := url.Parse(fmt.Sprintf(resolvedPingV1URL, scheme, c.registry))
`resolvedPingV1URL` is no longer used and can be removed.

2024-10-01 20:15 UTC, carlosrodfern commented
Thank you for the feedback. I believe I addressed all the comments. Let me know if it needs anything else :+1:

2024-10-02 13:11 UTC, mtrmac approved these changes
Thanks again!

2024-10-02 14:10 UTC, merged